#!/usr/bin/env bash                                                                                                                                                                                                                                                                                                                                                       

# Set up autograder files                                                                                                                                                                                                                                                                                                                                                 
if [ -f "/autograder/submission/blob.py" ]; then
    cp /autograder/submission/blob.py /autograder/source/python/blob.py

    if [ -f "/autograder/submission/avogadro.py" ]; then
	cp /autograder/submission/avogadro.py /autograder/source/python/avogadro.py
    else
	echo "Cannot find avogadro.py in submission. Is the file named correctly?"
    fi
    
    if [ -f "/autograder/submission/bead_tracker.py" ]; then
	cp /autograder/submission/bead_tracker.py /autograder/source/python/bead_tracker.py
    else
	echo "Cannot find bead_tracker.py in submission. Is the file named correctly?"
    fi
    
    cd /autograder/source
    python3 python/run_tests.py > /autograder/results/results.json

elif [ -f "/autograder/submission/Blob.java" ]; then
    cp /autograder/submission/Blob.java /autograder/source/java/Blob.java

    if [ -f "/autograder/submission/avogadro.py" ]; then
	cp /autograder/submission/Avogadro.java /autograder/source/java/avogadro.java
    else
	echo "Cannot find avogadro.py in submission. Is the file named correctly?"
    fi
    
    if [ -f "/autograder/submission/BeadTracker.java" ]; then
	cp /autograder/submission/BeadTracker.java /autograder/source/java/BeadTracker.java
    else
	echo "Cannot find bead_tracker.py in submission. Is the file named correctly?"
    fi

    if [ -f "/autograder/submission/BlobList.java" ]; then
	cp /autograder/submission/BlobList.java /autograder/source/java/BlobList.java
    else
	echo "Cannot find bead_tracker.py in submission. Is the file named correctly?"
    fi

    if [ -f "/autograder/submission/Luminance.java" ]; then
	cp /autograder/submission/Luminance.java /autograder/source/java/Luminance.java
    else
	echo "Cannot find bead_tracker.py in submission. Is the file named correctly?"
    fi

    if [ -f "/autograder/submission/Picture.java" ]; then
	cp /autograder/submission/Picture.java /autograder/source/java/Picture.java
    else
	echo "Cannot find bead_tracker.py in submission. Is the file named correctly?"
    fi

    if [ -f "/autograder/submission/Stdln.java" ]; then
	cp /autograder/submission/Stdln.java /autograder/source/java/Stdln.java
    else
	echo "Cannot find bead_tracker.py in submission. Is the file named correctly?"
    fi

    cd /autograder/source    
    # Compile the student's code with autograder code
    bash ./compile.sh

    # Run the autograder code
    bash ./run.sh > /autograder/results/results.json

## Write similar conditions and test execution for java code here as elif
else
  echo "Cannot find anagram.py or Anagram.java in submission. Is the file named correctly?"
fi


#- autograder
#    - source
#    - submission
#    - results
